config/routes.rb
Rails.application.routes.draw do
  

  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  namespace :api do
    resources :properties
  end

  namespace :api do
    namespace :v1 do
      resources :comments
    end
  end
  namespace :api do
    namespace :v1 do
     resources :appointments
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :properties do
      member do
        get:property_comments
        get:property_appointments
      end
    end
  end
end

namespace :api do
    resources :properties do
    member do
      get:property_comments
      get:property_appointments
    end
  end

end
  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/edit'
  get "/dashboard" => 'dashboard#index',as: :dashboard
  get 'dashboard/properties'
  get 'dashboard/report'
  devise_for :agents
  get 'public/main'
  resources:companies
  resources:agents do
    resources :comments
  end
  resources:properties do
    resources :comments
    resources :appointments, only: [:index, :new, :create]
  end

  resources:appointments do
    member do
      get 'properties_appointment'
    end
  end
  resources :users
  resources :propertytype
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'public#main'
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :agent
  has_many_attached :images
  has_many :comments, as: :commentable ,dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
  has_many :agents, through: :appointments 
  belongs_to :propertytype
  validates :name, presence:true, length: 5..100
  validates :address ,presence:true
  validates :descripition, length: 5..100, presence:true
  validates :price ,presence:true
  validates :propertytype_id, presence:true
  scope :with_property_name_contains, ->(app) { joins(:property).where("properties.name LIKE ?", "%#{app}%") }
  

end

app/models/propertytype.rb
class Propertytype < ApplicationRecord
has_many:properties
    validates :name, presence:true
    

end

app/controllers/api/properties_controller.rb
module Api
class Api::PropertiesController < ApplicationController

    def index
        @properties=Property.all 
        render json: {properties: @properties}
    end

    def show
        property = Property.find_by(id: params[:id])
        if property.present?
            render json: property, status: 200
        else
            render json: {error: " property is not exist"}
        end
      end

      def create
        @agent = Agent.find(doorkeeper_token.resource_owner_id)
        property= @agent.properties.new(property_params)
        if property.save
           render json: property, status: 200
        else 
           render json: {error: "not saved"}
        end
   
     end
     def update
      #debugger
      property = Property.find_by(id: params[:id])


      if current_agent.is_a? Agent
        if property.agent_id == doorkeeper_token.resource_owner_id
          if property.update(property_params)
            render json: {message: "property id #{property.id} is updated successfully"}
          else
            render json: {message:"property not updated"}
          end
        else
          render json:{error:"unauthorized"},status: :unauthorized
        end
      else
        render json: {error:"You are not allowed to updatee"},status: 403
      end
    end



    def destroy
      #debugger
      property=Property.find_by(id: params[:id])
     if property.present?
      if current_agent.is_a? Agent
         if property.agent_id == doorkeeper_token.resource_owner_id

          if property.destroy
            render json: {message: "property deleted"}
          else
            render json: {message:"Property not deleted"}
          end
        else
           render json:{error:"unauthorized"},status: :unauthorized
        end
      else
        render json: {message:"You are not allowed to delete"},status: 403
      end
     else 
        render json: {message:"message-not-found"}
     end
    end
    def property_comments
      property = Property.find(params[:id])
      count1 = property.comments.count
      render json: { no_of_comments_on_properties: count1 }
  
    end

    def property_appointments
      property=Property.find(params[:id])
      count2=property.appointments.count
      render json:{no_of_appointments_on_properties:count2}
    end

     private
  def property_params
    params.require(:property).permit(:name,:descripition,:price,:address,:agent_id , :propertytype_id, images: [])
  end

end
end

app/controllers/api/v1/properties_controller.rb
class Api::V1::PropertiesController < ActionController::API


#   skip_before_action:verify_authenticity_token
  def index
     properties=Property.all
     render json: properties, status:200
  end
  def show
    property = Property.find_by(id: params[:id])
    if property.present?
        render json: property, status: 200
    else
        render json: {error: " property is not exist"}
    end
  end
  def create
    
     property=Property.new(property_params)
     if property.save
        render json: property, status: 200
     else 
        render json: {error: "not saved"},status:422
     end

  end

  def update
    property = Property.find_by(id: params[:id])
          
     if property.nil?
      render json: { message: "Record not found" }, status: :not_found
     elsif  property.update(property_params) 

        render json: property, status: 200
    else
        render json: {error: "not updated"}, status: :unprocessable_entity
    end
  end
  def destroy
    property = Property.find_by(id: params[:id])
    property.destroy
    render json:{message: "Deleted"}
  end
  def property_comments
    property = Property.find(params[:id])
    count1 = property.comments.count
    render json: { no_of_comments_on_properties: count1 }

  end
  def property_appointments
    property=Property.find(params[:id])
    count2=property.appointments.count
    render json:{no_of_appointments_on_properties:count2}
  end
  private
  def property_params
    params.require(:property).permit(:name,:descripition,:price,:address,:agent_id , :propertytype_id, images: [])
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property,only: %i[:show, :edit, :update, :destroy]
  before_action :authenticate_agent!, only: [:new,:create,:destroy]
  def index
    @properties=Property.all
  end

  def show
   property_id
   @properties=Property.find(params[:id])
   @agents=Agent.all
   @commentable=@properties
   @comments=@commentable.comments if 
   @comment=Comment.new
   if @property.propertytype_id.present?
   @property_type_name = Propertytype.find(@property.propertytype_id).name
   end

  end
   def new
     @property=Property.new 
     @propertytype =Propertytype.all
   end
  def create
    @property = Property.new(property_params)
    
    @property.agent_id=current_agent.id
     respond_to do |format|
      if @property.save
      format.html{redirect_to @property,notice: 'property was succesfully created'}
      format.json{render :show,status: :created,location: @property}
     else
      format.html{render :new}
      format.json{render json:@property.errors, status: :unprocessable_entity}
     end
  end
end
 

  def edit
    property_id
  end
  def update
     property_id
     if @property.update(property_params)
      redirect_to property_path(@property)
     else
      render :edit
     end
  end
  def destroy
    property = Property.find(params[:id])
    property.appointments.destroy_all
    property.comments.destroy_all
    property.images.purge # or property.images.attachments.each(&:purge)
    property.users.destroy_all
    property.destroy
    redirect_to properties_path
  end
  private

  def property_params
    params.require(:property).permit(:name,:descripition,:price,:address,:agent_id , :propertytype_id, images: [])
  end

  def property_id
    @property=Property.find_by(id: params[:id])
  end
end

app/helpers/api/properties_helper.rb
module Api::PropertiesHelper
end

app/helpers/api/v1/properties_helper.rb
module Api::V1::PropertiesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper   
end

app/views/properties/_form.html.erb
<ol>
  <% @property.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ol>
<%= form_for @property do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br><br>

  <%= f.label :email %>
  <%= f.text_field :email %><br><br>
  <%= f.label :number %>
  <%= f.number_field :number %><br><br>

  <%= f.label :address %>
  <%= f.text_field :address%><br><br>
  <%= collection_select(:property,:agent_id,Agent.all,:id,:name,prompt:true)%>
  <%= f.submit %>
<% end %>

app/views/properties/edit.html.erb
<!-- <h1>Properties#edit</h1>
<p>Find me in app/views/properties/edit.html.erb</p>
<h3>Update  profile</h3>
<%= form_with model: @property do |ats| %>
     <%= ats.text_field :name,placeholder: "Property  name" %>
     <br>
     <br>
     <%= ats.text_field :descripition, placeholder:"enter the email address" %>

     <br>
     <br>
     <%= ats.text_field :price, placeholder:"Price" %>

     <br>
       
     <br>
     <br>
     <%= ats.text_field :address, placeholder:"enter the address" %>

     <br>
  <%= ats.file_field:image%>
  <br>
<br>
<br>
    <%= ats.submit class: "btn btn-primary"%>
<%end%>
 -->


 

<!-- <%= form_with model: @property do |f| %>
<div class="container">
    <div class="content">
       <img src="https://res.cloudinary.com/debbsefe/image/upload/f_auto,c_fill,dpr_auto,e_grayscale/image_fz7n7w.webp" alt="header-image" class="cld-responsive">
            <h1 class="form-title">Edit Here</h1>
            <form>
            <%= f.label :Name %>
            <%= f.text_field :name %>
            <div>
            <%= f.label :descripition %>
            <br>
            <%= f.text_field :descripition %>
            </div>
            <%= f.label :price %>
            <br>
            <%= f.number_field :price %>
            <br>
            
            <%= f.label :address %>
            <%= f.text_field :address%>
            
            <%= f.submit%>
            </form>
        </div>
 </div>
<% end%> -->


<ol>
  <% @property.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ol>

<%= form_with(model: @property) do |f| %>
<div class="container">
    <div class="content">
       <img src="https://res.cloudinary.com/debbsefe/image/upload/f_auto,c_fill,dpr_auto,e_grayscale/image_fz7n7w.webp" alt="header-image" class="cld-responsive">
            <h1 class="form-title">Register Here</h1>
            <form>
            <%= f.label :Name %>
            <br>
            <%= f.text_field :name %>
            <div>
            <br>
            <%= f.label :descripition %>
            <br>
            <%= f.text_field :descripition %>
            </div>
            <%= f.label :price %>
            <br>
            <%= f.number_field :price %>
            <br>
            
            <%= f.label :address %>
            <br>
            <%= f.text_field :address%>
            <br>
            
               <%= f.submit%>
            </form>
        </div>
 </div>
<% end%>

app/views/properties/index.html.erb
<div class="container-fluid">
        <main role="main">
        
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">Properties list of</h1>
            
          </div>
          <div class="table">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>id</th>
                  <th>Name of the properties</th>
                  <th>Posted By </th>
                  <th>Show</th>
                  <th>Edit</th>
                  <th>Destroy</th>
                </tr>
              </thead>
              <tbody>
              <% @properties.each do |pt| %>
              <%if pt.agent_id==current_agent.id%>
                <tr>
                <th scope="row"><%= pt.id%></th>
                  <td><%= pt.name %></td><>
                  <td><%= pt.agent.name%></td>
                 <td> <%= link_to 'show', property_path(pt) , style: "text-decoration: none;"%> </td>
                 <td> <%= link_to 'edit', edit_property_path(pt), style: "text-decoration: none;" %> </td>
                 <td><%= button_to 'remove',property_path(pt),method:'delete',data:"are you confirm" %></td>
                </tr>
                <%end%>
                <%end%>
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>







  
    

app/views/properties/new.html.erb
<ol>
  <% @property.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ol>

<%= form_with(model: @property) do |f| %>
<div class="container">
    <div class="content">
       <img src="https://res.cloudinary.com/debbsefe/image/upload/f_auto,c_fill,dpr_auto,e_grayscale/image_fz7n7w.webp" alt="header-image" class="cld-responsive">
            <h1 class="form-title">Register Here</h1>
            <form>
            <%= f.label :Name %>
            <br>
            <%= f.text_field :name %>
            <div>
            <br>
            <%= f.label :descripition %>
            <br>
            <%= f.text_field :descripition %>
            </div>
            <%= f.label :price %>
            <br>
            <%= f.number_field :price %>
            <br>
            
            <%= f.label :address %>
            <br>
            <%= f.text_field :address%>
            <br>
            <%= f.label :image %>
             <br>
            <%= f.file_field :images, multiple: true%>
            <br>
            <br>
            <p>Choose property</p>
            <br>
            <%= f.collection_select :propertytype_id, Propertytype.all, :id, :name, { prompt: true }, { class: 'form-control' } %>
            <br>
               <%= f.submit%>
            </form>
        </div>
 </div>
<% end%>

app/views/properties/show.html.erb
<!-- <% if @property.images.present? %>
<div class="row">
 <% (0...@property.images.count).each do  |image|%>
  <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
    <%= image_tag(@property.images[image] ,class:"img-fluid z-depth-1 ",style:"width:400px;height;700px;")%>
        
    </div>
    <%end%>
</div>
<% end %> -->


<div class="row1"style="padding:20px">
  <div class="">  
    <div class="card border-success mb-3 bg-light" style="width: 300px;
    height: 350px;
    margin-right: 3px;">
      <div class="card-header bg-transparent border-success">Property Details</div>
      <div class="card-body text-success">
        <h5 class="card-title text-dark"><%= @property.name%></h5>
        <p class="card-text text-dark"><%= @property.price%></p>
        <p class="card-text text-dark"><%= @property.address%></p>
        <p class="card-text text-dark"><%= @property.descripition%></p>
        <p class="card-text text-dark"><%= @property_type_name%></p>
      </div>
      <div class="card-footer bg-transparent border-success">
        <% if user_signed_in? %>
          <%= link_to 'Book Appointments',new_property_appointment_path(@property.id),method:'get' %>
        <%end %>
      </div>
    </div>
  </div>



<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% if @property.images.present? %>
      <% (0...@property.images.count).each do |index| %>
        <div class="carousel-item <%= 'active' if index == 0 %>">
          <%= image_tag @property.images[index],style: { height: '450px' }%>
        </div>
      <% end %>
    <% else %>
      <div class="carousel-item active">
        <img class="d-block w-100" src="..." alt="Placeholder image">
      </div>
    <% end %>
  </div>

  <% if @property.images.count > 1 %>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  <% end %>
</div>


  <div class="mb-4">  
    <div class="card border-success mb-3 bg-light" style="width: 300px;
    height: 350px;
   ">
      <div class="card-header bg-transparent border-success">Posted By</div>
      <div class="card-body text-success">
        <h5 class="card-title  text-dark"><%= @property.agent.name%></h5>
        <p class="card-text text-dark"><%= @property.agent.address %></p>
        <p class="card-text text-dark"><%= @property.agent.number %></p>
      </div>
      <div class="card-footer bg-transparent border-success">
        <% if agent_signed_in? && current_agent.id == @property.agent_id %>
          <!-- <%= link_to 'show Appointments', property_appointments_path(@property) %>  -->
          <%= button_to 'Edit',edit_property_path(@property),method:'get' , style: "text-decoration: none;"%>
          <%= button_to 'remove',property_path(@property),method:'delete',data:"are you confirm" %>
        <% end %> 
        <% if user_signed_in? %>
          <%= link_to 'Feedback to agent', agent_path(id: @property.agent.id),method:'get' %>
        <% end %>
      </div>
    </div>
  </div>
</div>





  

  




    




<%if user_signed_in?%>

    <div class="row d-flex justify-content-center">
  <div class="col-md-8 col-lg-6">
    <div class="card shadow-0 border" style="background-color: #f1d6b5;">
      <div class="card-body p-4">
        <div class="form-outline mb-4">
        <%= render "comments/commentform"%>
          <label class="form-label" for="addANote"></label>
        </div>
       <%= render "comments/commentouput"%>
      </div>
    </div>
  </div>
</div>
<%end%>