config/routes.rb
Rails.application.routes.draw do
  

  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  namespace :api do
    resources :properties
  end

  namespace :api do
    namespace :v1 do
      resources :comments
    end
  end
  namespace :api do
    namespace :v1 do
     resources :appointments
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :properties do
      member do
        get:property_comments
        get:property_appointments
      end
    end
  end
end

namespace :api do
    resources :properties do
    member do
      get:property_comments
      get:property_appointments
    end
  end

end
  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/edit'
  get "/dashboard" => 'dashboard#index',as: :dashboard
  get 'dashboard/properties'
  get 'dashboard/report'
  devise_for :agents
  get 'public/main'
  resources:companies
  resources:agents do
    resources :comments
  end
  resources:properties do
    resources :comments
    resources :appointments, only: [:index, :new, :create]
  end

  resources:appointments do
    member do
      get 'properties_appointment'
    end
  end
  resources :users
  resources :propertytype
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'public#main'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/agent.rb
class Agent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :company
  has_many :properties, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
  has_many :comments, as: :commentable
  #has_many :properties, through: :appointments
  validates :name, presence: true
  validates :address, length: { maximum: 20 }
  validate :password_format
  validates :email ,uniqueness: {message: ': An account associated with %{value} already exists'}



   #agent doorkeeper authorization
  def self.authenticate(email, password)

    agent=Agent.find_for_authentication(email: email)
    agent&.valid_password?(password) ? agent : nil
  end

  def password_format
    unless password.match?(/^(?=.*[A-Z])(?=.*\d).+$/)
      errors.add :password, 'must contain at least one uppercase letter and one digit'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :agent 
  belongs_to :property
  validate :appointment_date_cannot_be_in_the_past
  before_create :check_existing_appointment
def appointment_date_cannot_be_in_the_past
  if date.present? && date < Date.today
    errors.add(:date, "can't be in the past")
  end
end
def check_existing_appointment
  if Appointment.exists?(property_id: property_id, user_id: user_id)
    errors.add(:base, "You already have an appointment for this property.")
    throw :abort
  end
end

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true
    scope :property, ->{ where(:commentable_type => 'Property') }
    scope :agent, -> { where(:commentable_type => 'Agent') }
    validates:content ,presence:true
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :agents, dependent: :destroy
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :agent
  has_many_attached :images
  has_many :comments, as: :commentable ,dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
  has_many :agents, through: :appointments 
  belongs_to :propertytype
  validates :name, presence:true, length: 5..100
  validates :address ,presence:true
  validates :descripition, length: 5..100, presence:true
  validates :price ,presence:true
  validates :propertytype_id, presence:true
  scope :with_property_name_contains, ->(app) { joins(:property).where("properties.name LIKE ?", "%#{app}%") }
  

end

app/models/propertytype.rb
class Propertytype < ApplicationRecord
has_many:properties
    validates :name, presence:true
    

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :appointments
         has_many :properties , through: :appointments
         has_many :comments
         validates :name, presence: true
         validates :email, uniqueness: {message: ':this email is already exists please give another email for registration' }
        validates :email ,format: URI::MailTo::EMAIL_REGEXP

        def self.authenticate(email, password)
         # debugger
          user=User.find_for_authentication(email: email)
          user&.valid_password?(password) ? user : nil
        end

end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  def index
    @agents=Agent.all
    @companies=Company.all
  end

  def show
    agent_id
   @agents=Agent.find(params[:id])
   @companies=Company.all
   @commentable=@agents
   @comments=@commentable.comments
   @comment=Comment.new

  end
   def new
     @agent=Agent.new 
   end
  def create
    @agent = Agent.create(agent_params)
    if @agent.valid?
      redirect_to agents_index_path(@agent)
    else
      render :new
    end
  end
 

  def edit
    agent_id
  end
  def update
     agent_id
     if @agent.update(agent_params)
      redirect_to agent_path(@agent)
     else
      render :edit
     end
  end
  def destroy
    Agent.destroy(params[:id])
    
    redirect_to root_path
  end
  private

  def agent_params
    params.require(:agent).permit(:name,:age,:number, :email,:address,:company_id,:created_at)
  end

  def agent_id
    @agent=Agent.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable
  
  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment  = @commentable.comments.create(params.require(:comment).permit!)
    @comment.user_id=current_user.id

    if @comment.save
      redirect_to @commentable, notice: "Comment created."
      
    else
      render :new
    end
  end



  def destroy
    @comment = @commentable.comments.find(params[:id])
    @comment.destroy
    redirect_to @commentable, notice: "Comment deleted."
  end




private

  def load_commentable
    resource, id = request.path.split('/')[1, 2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end

  # alternative option:
  # def load_commentable
  #   klass = [Article, Photo, Event].detect { |c| params["#{c.name.underscore}_id"] }
  #   @commentable = klass.find(params["#{klass.name.underscore}_id"])
  # end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
  @properties=Property.all
  @users=User.all
  @agents=Agent.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
end

def new
    @user=User.new
end

def create
    # debugger
    @user=User.new(user_params)
    if @user.save
        redirect_to root_path
    else
        render 'new'
    end
end

def show
    @users=User.all

    @users=User.find_by(params[:id])

    
end
private
def user_params
    params.require(:user).permit(:name, :email, :number, :password)
end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper   
end

app/helpers/propertytype_helper.rb
module PropertytypeHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/agents/_form.html.erb
<ol>
  <% @agent.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ol>


<%= form_for @agent do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br><br>

  <%= f.label :email %>
  <%= f.text_field :email %><br><br>
  <%= f.label :number %>
  <%= f.number_field :number %><br><br>

  <%= f.label :address %>
  <%= f.text_field :address%><br><br>
  <%= collection_select(:agent,:company_id,Company.all,:id,:name,prompt:true)%>
  <%= f.submit %>
<% end %>

app/views/agents/edit.html.erb
<ol>
  <% @agent.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ol>


<%= form_for @agent do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br><br>

  <%= f.label :number %>
  <%= f.number_field :number %><br><br>

  <%= f.label :address %>
  <%= f.text_field :address%><br><br>
 
  <%= f.submit %>
<% end %>

app/views/agents/index.html.erb
<h1 style="text-align:center;color:green;">
            Agents  index page
        </h1>

    <table class="table table-bordered border-primary">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name of agent</th>
      <th scope="col">Edit Agent</th>
      <th scope="col">Remove Agent</th>
    </tr>
  </thead>

     <%if user_signed_in? %>
     <% @agents.each do |std| %>


     <tbody>
    <tr>
    
      <th scope="row"><%= std.id%></th>
      <td><%= link_to std.name, agent_path(std)%></td>

      <td><%= button_to 'Edit',edit_agent_path(std),method:'get' %></td>
      <td><%= button_to 'remove',agent_path(std),method:'delete',data:"are you confirm" %></td>
     
    </tr>
   
  </tbody>

  <%end %>
  <%else%>


   
  <% @agents.each do |std| %>

  <% if std.id == current_agent.id %>
  <tbody>
    <tr>
    
      <th scope="row"><%= std.id%></th>
      <td><%= link_to std.name, agent_path(std)%></td>

      <td><%= button_to 'Edit',edit_agent_path(std),method:'get' %></td>
      <td><%= button_to 'remove',agent_path(std),method:'delete',data:"are you confirm" %></td>
     
    </tr>
   
  </tbody>

  <%end %>
  <%end%>
  <%end%>
  
  
</table>



<div class="container">
    <div class="main-body">
    
          
          <!-- /Breadcrumb -->
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4><%=current_agent.name %></h4>
                      <p class="text-secondary mb-1">Regular Visitor</p>
                      <p class="text-muted font-size-sm"><%= current_agent.address %></p>
                      
                     <%= button_to 'remove',agent_path(current_agent.id),method:'delete',data:"are you confirm" %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  
                  
                  
                  
                  
               
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= current_agent.name %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= current_agent.email %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= current_agent.number %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Mobile</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      (320) 380-4539
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= current_agent.address %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12">
                      
                      <%= link_to "edit",  edit_agent_registration_path ,class:"btn btn-success" %>
                      <%= link_to "show property",  root_path ,class:"btn btn-success" %>
                      <%= link_to "show Appointments",  appointment_path(current_agent.id),class:"btn btn-success" %>
                       <%= link_to "show comments",  agent_path(current_agent.id),class:"btn btn-success" %>
                    </div>
                  </div>
                </div>
              </div>

              <div class="row gutters-sm">
               
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 mb-3">
                  
                    </div>
                  </div>
                </div>
              </div>



            </div>
          </div>

        </div>
    </div>


 

app/views/agents/new.html.erb
<h1>Agents#new</h1>
<p>Find me in app/views/agents/new.html.erb</p>


<ol>
  <% @agent.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ol>


<%= form_for @agent do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br><br>

  <%= f.label :email %>
  <%= f.text_field :email %><br><br>
  <%= f.label :number %>
  <%= f.number_field :number %><br><br>

  <%= f.label :address %>
  <%= f.text_field :address%><br><br>
  <%= collection_select(:agent,:company_id,Company.all,:id,:name,prompt:true)%>
  <%= f.submit %>
<% end %>

app/views/agents/show.html.erb
<h1 style="text-align:center;color:green;">
            Agent Profile 
        </h1>
<div class="container">
    <div class="main-body">
    
          
          <!-- /Breadcrumb -->
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4><%=@agent.name %></h4>
                      <p class="text-secondary mb-1">Regular Visitor</p>
                      <p class="text-muted font-size-sm"><%= @agent.address %></p>
                      <% if agent_signed_in?%>
                     <%= button_to 'remove',agent_path(@agent.id),method:'delete',data:"are you confirm" %>
                     <%end%>
                    </div>
              
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  
                  
                  
                  
                  
               
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @agent.name %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @agent.email %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%=@agent.number %>
                    </div>
                  </div>
                  <hr>
                 
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @agent.address %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12">
                      
                      <!-- <%= link_to "edit",  edit_agent_registration_path ,class:"btn btn-success" %> -->
                      <%= link_to "show property",  root_path ,class:"btn btn-success", style: "text-decoration: none;" %>
                      <%if agent_signed_in?%>
                      <%= link_to "show Appointments",  appointments_path,class:"btn btn-success" , style: "text-decoration: none;"%>
                      <%end%>
                       <%= link_to "show comments",  agent_path(@agent.id),class:"btn btn-success", style: "text-decoration: none;" %>
                    </div>
                  </div>
                </div>
              </div>

              <div class="row gutters-sm">
               
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 mb-3">
                  
                    </div>
                  </div>
                </div>
              </div>



            </div>
          </div>

        </div>
    </div>


 


 <%= render "comments/commentouput"%>
   <% if agent_signed_in?%>
   <%else%>
   <%= render "comments/commentform"%>
   <%end%>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1 class="d-flex flex-column align-items-center text-center" >Users Profile </h1>
<div class="container">
    <div class="main-body">
    
          
          <!-- /Breadcrumb -->
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4><%=current_user.name %></h4>
                      <p class="text-secondary mb-1">Regular Visitor</p>
                      <p class="text-muted font-size-sm"><%= current_user.address %></p>
                      <!-- <button class="btn btn-primary">Follow</button> -->
                      <!-- <button class="btn btn-outline-primary">Message</button> -->
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  
                  
                  
                  
                  
               
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= current_user.name %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= current_user.email %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= current_user.number %>
                    </div>
                  </div>
                  <hr>
                  <!-- <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Mobile</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      (320) 380-4539
                    </div>
                  </div> -->
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= current_user.address %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12">
                      
                      <!-- <%= link_to "edit",  edit_user_registration_path ,class:"btn btn-success" %> -->
                      <%= link_to "show property",  root_path ,class:"btn btn-success", style: "text-decoration: none;" %>
                      <%= link_to "show Appointments",  appointments_path,class:"btn btn-success" , style: "text-decoration: none;"%>
                    </div>
                  </div>
                </div>
              </div>

              <div class="row gutters-sm">
               
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 mb-3">
                  
                    </div>
                  </div>
                </div>
              </div>



            </div>
          </div>

        </div>
    </div>