config/routes.rb
Rails.application.routes.draw do
  

  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  namespace :api do
    resources :properties
  end

  namespace :api do
    namespace :v1 do
      resources :comments
    end
  end
  namespace :api do
    namespace :v1 do
     resources :appointments
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :properties do
      member do
        get:property_comments
        get:property_appointments
      end
    end
  end
end

namespace :api do
    resources :properties do
    member do
      get:property_comments
      get:property_appointments
    end
  end

end
  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/edit'
  get "/dashboard" => 'dashboard#index',as: :dashboard
  get 'dashboard/properties'
  get 'dashboard/report'
  devise_for :agents
  get 'public/main'
  resources:companies
  resources:agents do
    resources :comments
  end
  resources:properties do
    resources :comments
    resources :appointments, only: [:index, :new, :create]
  end

  resources:appointments do
    member do
      get 'properties_appointment'
    end
  end
  resources :users
  resources :propertytype
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'public#main'
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :agent 
  belongs_to :property
  validate :appointment_date_cannot_be_in_the_past
  before_create :check_existing_appointment
def appointment_date_cannot_be_in_the_past
  if date.present? && date < Date.today
    errors.add(:date, "can't be in the past")
  end
end
def check_existing_appointment
  if Appointment.exists?(property_id: property_id, user_id: user_id)
    errors.add(:base, "You already have an appointment for this property.")
    throw :abort
  end
end

end

app/controllers/api/v1/appointments_controller.rb
class Api::V1::AppointmentsController < ActionController::API


  def index
    appointments=Appointment.all
     render json: appointments, status:200
  end

  def show
    appointments=Appointment.find_by(id: params[:id])
    if appointments.present?
      render json: appointments, status:200
    else
      render json: {error: "there is not appointments"}
    end
  end

  def create
    appointments=Appointment.new(appointment_params)
    if appointments.save
      render json:appointments, status:200
    else
      render json:{error:"appointment is already exists"}
    end
  end
  def update
    appointments=Appointment.find_by(id: params[:id])
    if appointments.update(appointment_params)
      render json:appointments, status:200
    else
      render json:{error: "appointment is not update"}
    end
  end
  def destroy
    appointments=Appointment.find_by(id: params[:id])
     appointments.destroy
     render json:appointments

  end
  private
  def appointment_params
    params.require(:appointment).permit(:user_id, :agent_id, :date, :property_id)
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
# before_action :authenticate_account!, only: [:edit, :update, :destroy]
before_action :set_appointment, only: [:show, :edit, :update, :destroy]
#before_action :unauthorize_account, only: [:show, :edit, :update, :destroy]

def index
  if current_agent.present?
    @appointments = Appointment.joins(:property).where("properties.agent_id = ?", current_agent.id)
                               .includes(:agent, :property)
  elsif current_user.present?
    @appointments = Appointment.where(user_id: current_user.id)
                               .includes(:agent, :property)
  end
end

def new
  @appointment = Appointment.new
  @agents = Agent.all
  @property = Property.find(params[:property_id])
  @appointment.property_id = @property.id
end

def create
  @appointment = current_user.appointments.new(appointment_params)
  
  @appointment.property_id = params[:property_id]

  
  if @appointment.save
    redirect_to property_path(@appointment.property_id), notice: "Appointment created successfully."
  else
    @agents = Agent.all
    @property = Property.find(params[:property_id])
    
    render :new
  end
end
def edit
  @appointment = Appointment.find(params[:id])
  @agents = Agent.all
end


def update
  @appointment = Appointment.find(params[:id])
  if @appointment.update(appointment_params)
    redirect_to appointments_path, notice: "Appointment updated successfully."
  else
    @agents = Agent.all
    render :edit
  end
end

def show
  @property = @appointment.property

  if current_agent.present? && current_agent.id == @property.agent_id
    @appointments = current_agent.appointments.all
  elsif current_user.present?
    @appointments = current_user.appointments.all
  end
end

def destroy
  @appointment.destroy
  redirect_to appointments_path, notice: "Appointment deleted successfully."
end

# def properties_appointment
#   byebug
#   @property = Property.find_by(id: params[:id])
#   if current_agent.present?
#     @appointments = Appointment.joins(:property).where("appointment.property_id = ?", @property.id)
#                                .includes(:agent, :property)
#                                render :index
#   elsif current_user.present?
#     @appointments = Appointment.where(user_id: current_user.id)
#                                .includes(:agent, :property)
#   end
# end

# def unauthorize_account(@appointment)
#   user_appoint_id = @appointment.pluck(:user_id) if current_user.present?
#   agent_appoint_id = @appointment.pluck(:agent_id) if current_agent.present?
#   redirect_to root_path, alert: "Access denied." unless user_appoint_id.include?(current_user.id)  || agent_appoint_id.include?(current_agent.id)
# end

private

def set_appointment

  @appointment = Appointment.find(params[:id])
end

def appointment_params
  params.require(:appointment).permit(:user_id, :agent_id, :date, :property_id)
end




end

app/helpers/api/v1/appointments_helper.rb
module Api::V1::AppointmentsHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>

<%= form_with model: @appointment, url: appointment_path(@appointment), method: :put do |form| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>
      <ul>
        <% @appointment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date %>
    <%= form.date_field :date %>
    <%= form.submit "Save Appointment", class: "btn-success" %>
  </div>
<%end%>

app/views/appointments/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="text-center p-2">
        <h1>Appointments</h1>
      </div>

      <!--Table-->
      <table class="table table-striped w-auto">

        <!--Table head-->
        <thead>
          <tr>
            <th class="text-center">Appointment ID</th>
            <th class="text-center">User Name</th>
            <th class="text-center">Agent</th>
            <th class="text-center">Property</th>
            <th class="text-center">Date</th>
            <th class="text-center">Agent Address</th>
            <th class="text-center">Delete</th>
            <th class="text-center">Edit</th>
          </tr>
        </thead>
        <!--Table head-->

        <!--Table body-->
        <tbody>
          <% @appointments.each do |appointment| %>
          <tr class="table-info">
            <td class="text-center"><%= appointment.id %></td>
            <td class="text-center"><%= appointment.user.name %></td>
            <td class="text-center"><%= appointment.agent.name %></td>
            <td class="text-center"><%= appointment.property.name %></td>
            <td class="text-center"><%= appointment.date %></td>
            <td class="text-center"><%= appointment.agent.address %></td>
            <td class="text-center"><%= button_to "Delete", appointment_path(appointment), method: :delete, data: { confirm: "Are you sure?" } %></td>
            <td class="text-center"><%= link_to "Edit", edit_appointment_path(appointment) %></td>
          </tr>
          <% end %>
        </tbody>
        <!--Table body-->

      </table>
      <!--Table-->
    </div>
  </div>
</div>

<style>
  table {
    margin: 0 auto;
  }
</style>

app/views/appointments/new.html.erb
<!-- <h1>New Appointment</h1>

<%= form_with model: @appointment, url: appointments_path do |form| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>
      <ul>
        <% @appointment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :agent_id, "Agent" %>
    <%= form.collection_select :agent_id, @agents, :id, :name, prompt:true%>
  </div>

  <div>
    <%= form.submit "Create Appointment" %>
  </div>
<% end %> -->

<% if @appointment.errors.any? %>
  <div class="alert alert-danger">
    <% @appointment.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
<% end %>




<%= link_to "Back", appointments_path %>
<%= form_with(model: [@property, @appointment], url: property_appointments_path(@property)) do |form| %>
  <%= form.hidden_field :property_id, value: @property.id %>
  <%= form.hidden_field :agent_id, value: @property.agent.id %>
  <div>
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>
  <%= form.submit 'Book Appointment' %>
<% end %>

app/views/appointments/show.html.erb
<div class="text-center p-2"><h1>Appointments ka show page </h1></div>

<h1> </h1>

<%= link_to "New Appointment", new_appointment_path%>


<!--Table-->
<table class="table table-striped w-auto">

  <!--Table head-->
  <thead>
    <tr>
      <th>Number</th>
      <th>User name</th>
      <th>Agent</th>
      <th>property</th>
      <th>Date</th>
      <th>Agent Address</th>
      <th>Delete</th>
      <th>Edit</th>
    </tr>
  </thead>
  <!--Table head-->

  <!--Table body-->
<% @appointments.each do |appointment| %>
  <tbody>
   <%if appointment.property.id == @property.id%>
    <tr class="table-info">
      <th scope="row"><%= appointment.id %></th>
      <td><%= appointment.try(:user).name%></td>
      <td><%= appointment.agent.name%></td>
      <td><%= appointment.property.name%>
      <td><%= appointment.date%></td>
      <td><%= appointment.agent.address%></td>
      <td><%= button_to "Delete", appointment_path(appointment), method: :delete, data: { confirm: "Are you sure?" } %></td>
      <td><%= link_to "Edit", edit_appointment_path(appointment) %></td>
    </tr>
  </tbody>
  <!--Table body-->
<%end%>
<%end%>
</table>
<!--Table-->