config/routes.rb
Rails.application.routes.draw do
  

  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  namespace :api do
    resources :properties
  end

  namespace :api do
    namespace :v1 do
      resources :comments
    end
  end
  namespace :api do
    namespace :v1 do
     resources :appointments
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :properties do
      member do
        get:property_comments
        get:property_appointments
      end
    end
  end
end

namespace :api do
    resources :properties do
    member do
      get:property_comments
      get:property_appointments
    end
  end

end
  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/edit'
  get "/dashboard" => 'dashboard#index',as: :dashboard
  get 'dashboard/properties'
  get 'dashboard/report'
  devise_for :agents
  get 'public/main'
  resources:companies
  resources:agents do
    resources :comments
  end
  resources:properties do
    resources :comments
    resources :appointments, only: [:index, :new, :create]
  end

  resources:appointments do
    member do
      get 'properties_appointment'
    end
  end
  resources :users
  resources :propertytype
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'public#main'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/agent.rb
class Agent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :company
  has_many :properties, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
  has_many :comments, as: :commentable
  #has_many :properties, through: :appointments
  validates :name, presence: true
  validates :address, length: { maximum: 20 }
  validate :password_format
  validates :email ,uniqueness: {message: ': An account associated with %{value} already exists'}



   #agent doorkeeper authorization
  def self.authenticate(email, password)

    agent=Agent.find_for_authentication(email: email)
    agent&.valid_password?(password) ? agent : nil
  end

  def password_format
    unless password.match?(/^(?=.*[A-Z])(?=.*\d).+$/)
      errors.add :password, 'must contain at least one uppercase letter and one digit'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :agent 
  belongs_to :property
  validate :appointment_date_cannot_be_in_the_past
  before_create :check_existing_appointment
def appointment_date_cannot_be_in_the_past
  if date.present? && date < Date.today
    errors.add(:date, "can't be in the past")
  end
end
def check_existing_appointment
  if Appointment.exists?(property_id: property_id, user_id: user_id)
    errors.add(:base, "You already have an appointment for this property.")
    throw :abort
  end
end

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true
    scope :property, ->{ where(:commentable_type => 'Property') }
    scope :agent, -> { where(:commentable_type => 'Agent') }
    validates:content ,presence:true
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :agents, dependent: :destroy
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :agent
  has_many_attached :images
  has_many :comments, as: :commentable ,dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
  has_many :agents, through: :appointments 
  belongs_to :propertytype
  validates :name, presence:true, length: 5..100
  validates :address ,presence:true
  validates :descripition, length: 5..100, presence:true
  validates :price ,presence:true
  validates :propertytype_id, presence:true
  scope :with_property_name_contains, ->(app) { joins(:property).where("properties.name LIKE ?", "%#{app}%") }
  

end

app/models/propertytype.rb
class Propertytype < ApplicationRecord
has_many:properties
    validates :name, presence:true
    

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :appointments
         has_many :properties , through: :appointments
         has_many :comments
         validates :name, presence: true
         validates :email, uniqueness: {message: ':this email is already exists please give another email for registration' }
        validates :email ,format: URI::MailTo::EMAIL_REGEXP

        def self.authenticate(email, password)
         # debugger
          user=User.find_for_authentication(email: email)
          user&.valid_password?(password) ? user : nil
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
end

def new
    @user=User.new
end

def create
    # debugger
    @user=User.new(user_params)
    if @user.save
        redirect_to root_path
    else
        render 'new'
    end
end

def show
    @users=User.all

    @users=User.find_by(params[:id])

    
end
private
def user_params
    params.require(:user).permit(:name, :email, :number, :password)
end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper   
end

app/helpers/propertytype_helper.rb
module PropertytypeHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<!-- <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
     
     <h5> <%= link_to 'HOUSE4U', root_path ,class: 'p-2 text-dark'%> </h5>
      <nav class="my-2 my-md-0 mr-md-3">
       
        <%= link_to 'Create company', new_company_path,class: 'p-2 text-dark'%>
        <%= link_to 'Show Property', properties_path ,class: 'p-2 text-dark'%>
        <%= link_to 'Agent section', agents_path ,class: 'p-2 text-dark'%>
        <a class="p-2 text-dark" href="#">User Section</a>
      </nav>
    
    </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Housing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

<% if ["public","devise"].include?(controller.controller_name) %>
<header>
<%= render "layouts/nav/public" %>
</header>
 <% else %>
 <%= render "layouts/nav/dashboard" %>
 <%end %>
  
  <%= yield %>



<div id="notifications"><%= notice %> </div>



  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 
  
  </body>
</html>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar sticky-top navbar-expand-lg " style="background-color: #a1cfe7;">
  <a class="navbar-brand" style="text-decoration:none !important;"href="#"> House4U</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ">
      <li class="nav-item active">
        <%=link_to "Home" ,root_path,class:"nav-link", style: "text-decoration: none;"%><span class="sr-only">(current)</span>
      </li>
        
      <li class="nav-item" style="margin-top:16px;font-size:1.4em">
      <%if user_signed_in?%>
        <%= link_to "show property",  root_path, style: "text-decoration: none;"%>
        <%end%>
      </li>
      <li class="nav-item" style="margin-top:16px;font-size:1.4em">
        <%if agent_signed_in?%>
        <%= link_to "List of property" ,properties_path , style: "text-decoration: none;"%>
        <%= link_to 'Create property',new_property_path, style: "text-decoration: none;" %>
         <!-- <%= link_to 'Show Comments',agents_path(current_agent.id) %> -->
        <%end%>
      </li>
      <% if agent_signed_in? %>
        <li class="nav-item text-nowrap">
          <%= button_to "sign Out" ,destroy_agent_session_path, method: :delete,class:"btn btn-lg btn-block", style:"margin-top: 19px;"%>
        </li>
        <% elsif user_signed_in?  %>
        <li class="nav-item" >
        <%= button_to "sign Out" ,destroy_user_session_path, method: :delete,class:"btn btn-lg btn-block ",style:"margin-top: -6px;" %>
      </li>
      <%end%>
    </ul>
    
  </div>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-lg " style="background-color: #a1cfe7;">
<div class="container-fluid">
  <a class="navbar-brand" href="#">House4U</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
      <% if agent_signed_in? %>
        <%= link_to "Agent profile", agent_path(current_agent.id), class: "nav-link", style: "text-decoration: none;"

 %>
         <% elsif user_signed_in? %>
         <%= link_to "User profile", user_path(current_user.id), class: "nav-link", style: "text-decoration: none;" %>
         
         <%end %>
      </li>
      
      <li class="nav-item" style="margin-top:16px;font-size:1.4em">
      <%if user_signed_in?%>
         <%= link_to "show Appointments",  appointments_path, class:"button_to"%>
        <%end%>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      <% if agent_signed_in? %>
      <li class="nav-item" ,style="margin-top: -6px;margin-right:1200px">
       <%= button_to "logout" , destroy_agent_session_path ,method: :delete %>
      </li>
      <% elsif user_signed_in? %>
      <li class="nav-item">
      <%= button_to "logout", destroy_user_session_path, method: :delete, style: { "margin-right" => "1200px" } %>

     </li>
      <% else %>
      <li class="nav-item">
      <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style= "text-decoration: none;">
      Login
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="agents/sign_in" style= "text-decoration: none;">Login As Agent</a>
      <a class="dropdown-item" href="users/sign_in" style= "text-decoration: none;">Login As User</a>

    <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style= "text-decoration: none;">
      SignUp
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="agents/sign_up" style= "text-decoration: none;">Register As Agent</a>
      <a class="dropdown-item" href="users/sign_up" style= "text-decoration: none;">Register As User</a>
      <div class="dropdown-divider"></div>
    </div>
      <% end %>




      <li class="nav-item">
        <a class="nav-link"></a>
      </li>
   

      























    </ul>
  </div>
</div>
</nav>

app/views/layouts/nav/_sidebardashboard.html.erb
<div class="row">
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to dashboard_path,class:"nav-link" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
          Dashboard <span class="sr-only">(current)</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to properties_path,class:"nav-link" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
          Properties
        <%end %>
      </li>
      <li class="nav-item">
         <%= link_to agents_path(current_agent.id),class:"nav-link" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
          Agent details 
        <%end %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">

        </a>
      </li>
      <li class="nav-item">
         <%= link_to root_path(current_agent.id),class:"nav-link" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
          Go to Homepage 
        <%end %>
      </li>
      <li class="nav-item">
  
      </li>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">

    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        
      </li>
      <li class="nav-item">
       
      </li>
      <li class="nav-item">
        
      </li>
      <li class="nav-item">
        
      </li>
    </ul>
  </div>
</nav>